import React from 'react';
import { ReportControls } from './ReportControls';
import { ShareReportButton } from './ShareReportButton';

interface ReportLayoutProps {
  children: React.ReactNode;
  title: string;
  dateRange: string;
  days?: number;
  siteId?: string; // Added for share functionality
}

export function ReportLayout({ children, title, dateRange, days, siteId }: ReportLayoutProps) {
  return (
    <div className="min-h-screen bg-white text-gray-900 p-8 print:p-0 font-sans">
      {/* Print-only CSS to enforce layout */}
      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          @page {
            margin: 20mm;
            size: A4;
          }
          body {
            -webkit-print-color-adjust: exact;
          }
          .no-print, [class*="cookie"] {
            display: none !important;
          }
        }
      `}} />

      {/* Header */}
      <header className="flex justify-between items-center mb-12 border-b border-gray-200 pb-6 break-inside-avoid">
        <div className="flex items-center gap-4">
          {/* Logo */}
          <div className="w-12 h-12 flex-shrink-0">
             {/* eslint-disable-next-line @next/next/no-img-element */}
             <img src="/images/logo.png" alt="Navlens Logo" className="w-full h-full object-contain" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight leading-none">Navlens Analytics</h1>
            <p className="text-sm text-indigo-600 font-medium mt-1">navlensanalytics.com</p>
          </div>
        </div>
        <div className="text-right flex flex-col items-end gap-2">
          <div className="text-2xl font-bold text-gray-900">{title.replace('Performance Report: ', '')}</div>
          <div className="flex items-center gap-3">
            {typeof days === 'number' && <ReportControls currentDays={days} />}
            <p className={`text-gray-500 font-medium ${typeof days === 'number' ? 'print:block hidden' : ''}`}>{dateRange}</p>
          </div>
          {/* Share button (only shown when siteId is available, hidden in print) */}
          {siteId && typeof days === 'number' && (
            <ShareReportButton siteId={siteId} days={days} />
          )}
        </div>
      </header>

      {/* Report Content */}
      <main className="space-y-8">
        {children}
      </main>

      {/* Report Footer */}
      <footer className="mt-12 pt-6 border-t border-gray-200 flex justify-between items-center text-sm text-gray-500">
        <div>Generated by Navlens Analytics</div>
        <div>{new Date().toLocaleDateString()}</div>
      </footer>
    </div>
  );
}
